"""Type stub for marisa_trie to satisfy static analysis and IDE language servers."""
from typing import Any, Iterable, List, Tuple, Union, Optional

class _Trie:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: Any) -> bool: ...
    def keys(self, prefix: str = "") -> List[str]: ...
    def prefixes(self, key: str) -> List[str]: ...
    def has_keys_with_prefix(self, prefix: str) -> bool: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...
    def mmap(self, path: str) -> None: ...

class Trie(_Trie):
    def __init__(self, arg: Optional[Iterable[str]] = None, **options: Any) -> None: ...

class BytesTrie(_Trie):
    def __init__(self, arg: Optional[Iterable[Tuple[str, bytes]]] = None, **options: Any) -> None: ...
    def __getitem__(self, key: str) -> List[bytes]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def items(self, prefix: str = "") -> List[Tuple[str, bytes]]: ...

class RecordTrie(_Trie):
    def __init__(self, fmt: str, arg: Optional[Iterable[Tuple[str, tuple]]] = None, **options: Any) -> None: ...

class BinaryTrie(_Trie):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
